[package]
name = "my_collection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.5", features = ["macros"] }
serde = { version = "1.0.197", features = ["derive"] }
chrono = { version = "0.4.37", features = ["serde"] }
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
async-trait = "0.1.80"
