services:
  web:
    build: MyCollectionSite
    ports:
      - "443:443"
    volumes:
      - content:/usr/share/nginx/mycollection/content
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - content:/content/
    environment:
      SECRET: Placeholder
      CONTENT_DISPLAY_PATH: https://localhost/images/
      DATABASE_URL: postgresql://postgres:Placeholder@db:5432/collectiondb
      SERVER_URL: https://localhost/
      CONTENT_PATH: /content/
      API_URL: https://localhost/api/
  db:
    build: Database
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Placeholder

volumes:
  content:
  pg-data:

